/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Returns a deterministic hardware fingerprint (SHA-256 hash of the machine UID).
 * This is used to lock license keys to a specific physical device.
 */
export declare function getHardwareId(): string
/**
 * Validates a Gumroad license key by calling the Gumroad Licenses API.
 * Returns "OK" on success, or an error message string on failure.
 *
 * Tries both the product_id and permalink to handle both old and new Gumroad products.
 */
export declare function verifyGumroadKey(licenseKey: string): string
export interface AudioDeviceInfo {
  id: string
  name: string
}
export declare function getInputDevices(): Array<AudioDeviceInfo>
export declare function getOutputDevices(): Array<AudioDeviceInfo>
export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null)
  getSampleRate(): number
  /**
   * Pre-warm SCK: spawn the background thread to do the slow ScreenCaptureKit
   * initialization (ShareableContent + stream start). Audio data is captured
   * but discarded until a callback is provided via start().
   * Call this early (e.g. 2s after app launch via setTimeout) so SCK is ready
   * before the user ever clicks "Start Natively".
   */
  warmup(): void
  /**
   * Set the JS callback for audio data. If warmup() was called earlier,
   * audio will start flowing immediately. If not, this also triggers warmup.
   */
  start(callback: (...args: any[]) => any): void
  pauseCapture(): void
  stop(): void
}
export declare class MicrophoneCapture {
  constructor(deviceId?: string | undefined | null)
  getSampleRate(): number
  start(callback: (...args: any[]) => any): void
  stop(): void
}
