/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Returns a deterministic hardware fingerprint (SHA-256 hash of the machine UID).
 * This is used to lock license keys to a specific physical device.
 */
export declare function getHardwareId(): string
/**
 * Validates a Gumroad license key by calling the Gumroad Licenses API.
 * Returns "OK" on success, or an error message string on failure.
 * Calls are made in a background thread to prevent blocking the Node.js event loop.
 */
export declare function verifyGumroadKey(licenseKey: string, callback: (...args: any[]) => any): void
export interface AudioDeviceInfo {
  id: string
  name: string
}
export declare function getInputDevices(): Array<AudioDeviceInfo>
export declare function getOutputDevices(): Array<AudioDeviceInfo>
export declare class SystemAudioCapture {
  constructor(deviceId?: string | undefined | null)
  getSampleRate(): number
  start(callback: (...args: any[]) => any, onSpeechEnded?: (...args: any[]) => any | undefined | null): void
  stop(): void
}
export declare class MicrophoneCapture {
  constructor(deviceId?: string | undefined | null)
  getSampleRate(): number
  start(callback: (...args: any[]) => any, onSpeechEnded?: (...args: any[]) => any | undefined | null): void
  stop(): void
}
